export const codes = {
  0: { description: "Clear sky", imagePath: '../images/clear-day.svg' },
  1: { description: "Mainly clear", imagePath: '../images/partly-cloudy-day.svg' },
  2: { description: "Partly cloudy", imagePath: '../images/partly-cloudy-day.svg' },
  3: { description: "Overcast", imagePath: '../images/overcast.svg' },
  45: { description: "Fog", imagePath: '../images/fog.svg' },
  48: { description: "Fog", imagePath: '../images/fog.svg' },
  51: { description: "Drizzle: Light intensity", imagePath: '../images/drizzle.svg' },
  53: { description: "Drizzle: Moderate intensity", imagePath: '../images/drizzle.svg' },
  55: { description: "Drizzle: Dense intensity", imagePath: '../images/drizzle.svg' },
  56: { description: "Freezing Drizzle: Light intensity", imagePath: '../images/drizzle.svg' },
  57: { description: "Freezing Drizzle: Dense intensity", imagePath: '../images/drizzle.svg' },
  61: { description: "Rain: Slight intensity", imagePath: '../images/rain.svg' },
  63: { description: "Rain: Moderate intensity", imagePath: '../images/rain.svg' },
  65: { description: "Rain: Heavy intensity", imagePath: '../images/rain.svg' },
  66: { description: "Freezing Rain: Light intensity", imagePath: '../images/rain.svg' },
  67: { description: "Freezing Rain: Heavy intensity", imagePath: '../images/rain.svg' },
  71: { description: "Snowfall: Slight intensity", imagePath: '../images/snow.svg' },
  73: { description: "Snowfall: Moderate intensity", imagePath: '../images/snow.svg' },
  75: { description: "Snowfall: Heavy intensity", imagePath: '../images/snow.svg' },
  77: { description: "Snow grains", imagePath: '../images/snow.svg' },
  80: { description: "Rain showers: Slight intensity", imagePath: '../images/rain.svg' },
  81: { description: "Rain showers: Moderate intensity", imagePath: '../images/rain.svg' },
  82: { description: "Rain showers: Violent intensity", imagePath: '../images/rain.svg' },
  85: { description: "Snow showers: Slight intensity", imagePath: '../images/snow.svg' },
  86: { description: "Snow showers: Heavy intensity", imagePath: '../images/snow.svg' },
  95: { description: "Thunderstorm: Slight or moderate", imagePath: '../images/thunderstorms.svg' },
  96: { description: "Thunderstorm with slight hail", imagePath: '../images/thunderstorms.svg' },
  99: { description: "Thunderstorm with heavy hail", imagePath: '../images/thunderstorms.svg' }
};
